#--------------------------------------------------------------------
#       Locale
#--------------------------------------------------------------------
quarkus.default-locale=it-IT
#--------------------------------------------------------------------
#				OpenAPI and Swagger
#--------------------------------------------------------------------
%dev.quarkus.smallrye-openapi.info-title=Rendcore API
%dev.quarkus.smallrye-openapi.info-version=1.0.0
%dev.quarkus.swagger-ui.doc-expansion=none
%dev.quarkus.smallrye-openapi.security-scheme=jwt
%dev.quarkus.smallrye-openapi.path=/docs/v1/openapi
%dev.quarkus.smallrye-openapi.operation-id-strategy=method
%dev.quarkus.swagger-ui.path=/ui/v1/openapi
%dev.quarkus.swagger-ui.display-operation-id=true
%dev.quarkus.swagger-ui.always-include=true
#--------------------------------------------------------------------
#				Health
#--------------------------------------------------------------------
quarkus.smallrye-health.root-path=/api/v1/health
quarkus.smallrye-health.ui.root-path=/ui/v1/health
#--------------------------------------------------------------------
#				Server properties
#--------------------------------------------------------------------
quarkus.http.root-path=/api/v1/rendcore
quarkus.http.port=8090
quarkus.http.test-port=8091
quarkus.http.limits.max.body.size=20M
#--------------------------------------------------------------------
#               DB config
#--------------------------------------------------------------------
quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/rendcore_budget_db?currentSchema=dev,public
%dev.quarkus.datasource.username=rendcore_budget
%dev.quarkus.datasource.password=rendcore_budget

#--------------------------------------------------------------------
#               Flyway Migration
#--------------------------------------------------------------------
quarkus.flyway.locations=dbinit/postgres
quarkus.flyway.enabled=false
quarkus.flyway.migrate-at-start=false
quarkus.flyway.ignore-missing-migrations=false
%dev.quarkus.flyway.enabled=true
%dev.quarkus.flyway.migrate-at-start=true
%dev.quarkus.flyway.ignore-missing-migrations=false

#--------------------------------------------------------------------
#				CORS
#--------------------------------------------------------------------
quarkus.http.cors.enabled=true
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.headers=Authorization,Access-Control-Allow-Origin,Content-Type,Response-Type

#--------------------------------------------------------------------
#				CLIENT REST
#--------------------------------------------------------------------

rendcore-employee=http://localhost:8070/api/v1/rendcore-employee

#--------------------------------------------------------------------
#				CACHE
#--------------------------------------------------------------------

quarkus.cache.enabled=true
quarkus.cache.caffeine.employee-summary-cache.maximum-size=10000
quarkus.cache.caffeine.employee-summary-cache.expire-after-write=24H

quarkus.cache.caffeine.status-transition-cache.maximum-size=100
quarkus.cache.caffeine.status-transition-cache.expire-after-write=4380H

# ============================================
# XLSX Export Configuration
# ============================================

# Maximum number of months between 'from' and 'to' for which
# Excel sheets are generated monthly.
# If the range is:
#   <= this value monthly sheets
#   > this value quarterly sheets
xlsx.config.months-sheet=12

# Maximum number of months between 'from' and 'to' for which
# Excel sheets are generated quarterly.
# If the range is:
#   > months-sheet and <= this value  quarterly sheets
#   > this value  yearly sheets
xlsx.config.quarters-sheet=36

xlsx.config.auto-size-columns=true
xlsx.config.freeze-header=true
xlsx.config.zoom-level=85

#--------------------------------------------------------------------
#				MISC
#--------------------------------------------------------------------
quarkus.jacoco.enabled=true
quarkus.keycloak.devservices.enabled=false
quarkus.log.category."io.quarkus.mailer".level=DEBUG
quarkus.log.category."io.ebean.SQL".level=DEBUG
quarkus.log.category."io.ebean.TXN".level=DEBUG




