-- apply changes
create table budget_request (
  id                            uuid not null,
  description                   TEXT not null,
  user_request_id               uuid not null,
  _version                      bigint not null,
  _created_at                   timestamptz not null,
  _updated_at                   timestamptz not null,
  amount                        decimal(12,2) not null,
  title                         varchar(255) not null,
  currency                      varchar(3) not null,
  transaction_type              varchar(7) not null,
  budget_status_id              varchar(255) not null,
  budget_type_id                varchar(255),
  _created_by                   varchar(255) not null,
  _updated_by                   varchar(255) not null,
  constraint ck_budget_request_transaction_type check ( transaction_type in ('INCOME','EXPENSE')),
  constraint pk_budget_request primary key (id)
);

create table budget_status_change (
  id                            uuid not null,
  request_id                    uuid not null,
  performed_by                  uuid not null,
  note                          TEXT,
  _version                      bigint not null,
  _created_at                   timestamptz not null,
  _updated_at                   timestamptz not null,
  old_status_id                 varchar(255) not null,
  new_status_id                 varchar(255) not null,
  _created_by                   varchar(255) not null,
  _updated_by                   varchar(255) not null,
  constraint pk_budget_status_change primary key (id)
);

create table budget_status_transition (
  id                            bigint generated by default as identity not null,
  from_status_id                varchar(255) not null,
  to_status_id                  varchar(255) not null,
  constraint pk_budget_status_transition primary key (id)
);

create table budget_status_type (
  id                            varchar(255) not null,
  description                   varchar(255) not null,
  constraint pk_budget_status_type primary key (id)
);

create table budget_type (
  id                            varchar(255) not null,
  description                   varchar(255) not null,
  constraint pk_budget_type primary key (id)
);

-- apply alter tables
alter table budget_request add column if not exists sys_period tstzrange not null default tstzrange(current_timestamp, null);
-- apply post alter
update budget_request set sys_period = tstzrange(_created_at, null);
create table budget_request_history(like budget_request);
create view budget_request_with_history as select * from budget_request union all select * from budget_request_history;
create or replace function budget_request_history_version() returns trigger as $$
declare
  lowerTs timestamptz;
  upperTs timestamptz;
begin
  lowerTs = lower(OLD.sys_period);
  upperTs = greatest(lowerTs + '1 microsecond',current_timestamp);
  if (TG_OP = 'UPDATE') then
    insert into budget_request_history (sys_period,id, title, description, amount, currency, user_request_id, transaction_type, budget_status_id, budget_type_id, _version, _created_at, _created_by, _updated_at, _updated_by) values (tstzrange(lowerTs,upperTs), OLD.id, OLD.title, OLD.description, OLD.amount, OLD.currency, OLD.user_request_id, OLD.transaction_type, OLD.budget_status_id, OLD.budget_type_id, OLD._version, OLD._created_at, OLD._created_by, OLD._updated_at, OLD._updated_by);
    NEW.sys_period = tstzrange(upperTs,null);
    return new;
  elsif (TG_OP = 'DELETE') then
    insert into budget_request_history (sys_period,id, title, description, amount, currency, user_request_id, transaction_type, budget_status_id, budget_type_id, _version, _created_at, _created_by, _updated_at, _updated_by) values (tstzrange(lowerTs,upperTs), OLD.id, OLD.title, OLD.description, OLD.amount, OLD.currency, OLD.user_request_id, OLD.transaction_type, OLD.budget_status_id, OLD.budget_type_id, OLD._version, OLD._created_at, OLD._created_by, OLD._updated_at, OLD._updated_by);
    return old;
  end if;
end;
$$ LANGUAGE plpgsql;

create trigger budget_request_history_upd
  before update or delete on budget_request
  for each row execute procedure budget_request_history_version();


-- foreign keys and indices
create index ix_budget_request_budget_status_id on budget_request (budget_status_id);
alter table budget_request add constraint fk_budget_request_budget_status_id foreign key (budget_status_id) references budget_status_type (id) on delete restrict on update restrict;

create index ix_budget_request_budget_type_id on budget_request (budget_type_id);
alter table budget_request add constraint fk_budget_request_budget_type_id foreign key (budget_type_id) references budget_type (id) on delete restrict on update restrict;

create index ix_budget_status_change_request_id on budget_status_change (request_id);
alter table budget_status_change add constraint fk_budget_status_change_request_id foreign key (request_id) references budget_request (id) on delete restrict on update restrict;

create index ix_budget_status_change_old_status_id on budget_status_change (old_status_id);
alter table budget_status_change add constraint fk_budget_status_change_old_status_id foreign key (old_status_id) references budget_status_type (id) on delete restrict on update restrict;

create index ix_budget_status_change_new_status_id on budget_status_change (new_status_id);
alter table budget_status_change add constraint fk_budget_status_change_new_status_id foreign key (new_status_id) references budget_status_type (id) on delete restrict on update restrict;

create index ix_budget_status_transition_from_status_id on budget_status_transition (from_status_id);
alter table budget_status_transition add constraint fk_budget_status_transition_from_status_id foreign key (from_status_id) references budget_status_type (id) on delete restrict on update restrict;

create index ix_budget_status_transition_to_status_id on budget_status_transition (to_status_id);
alter table budget_status_transition add constraint fk_budget_status_transition_to_status_id foreign key (to_status_id) references budget_status_type (id) on delete restrict on update restrict;

create index if not exists ix_budget_request_title on budget_request (title);
create index if not exists ix_budget_request_amount on budget_request (amount);
create index if not exists ix_budget_request_user_request_id on budget_request (user_request_id);
create index if not exists ix_budget_request_transaction_type on budget_request (transaction_type);
create index if not exists ix_budget_status_change_performed_by on budget_status_change (performed_by);
create index if not exists from_to_status on budget_status_transition (from_status_id,to_status_id);
